apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: custom-addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - git:
              repoURL: '{{ index .metadata.annotations "gitops_repo_url" }}'
              revision: '{{ index .metadata.annotations "gitops_repo_revision" }}'
              directories:
                - path: gitops/custom-addons/charts/*
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]
  template:
    metadata:
      name: 'custom-{{ .path.basename }}'
    spec:
      project: custom-addons
      source:
        repoURL: '{{ .metadata.annotations.gitops_repo_url }}'
        targetRevision: '{{ .metadata.annotations.gitops_repo_revision }}'
        path: '{{ .path.path }}'
      destination:
        server: '{{ .server }}'
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    {{- if eq (.path.basename) "velero-infra" }}
    spec:
      source:
        helm:
          valuesObject:
            clusterName: {{ .metadata.annotations.cluster_name }}
            accountId: "{{ .metadata.annotations.aws_account_id }}"
    {{- end }}
    {{- if eq (.path.basename) "cis-benchmark" }}
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true
    {{- end }}
